apiVersion: v1
kind: Service
metadata:
  name: wli-myapp-service
  namespace: default
spec:
  selector:
    app: wli-myapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP