# Default values for wli-myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/makdeniz/wli-myapp 
  tag: "latest"

serviceAccount:
  name: "sa-uaid-myapp" 
  clientId: "client-id-myapp"

service:
  type: ClusterIP
  port: 3000

env:
  PG_HOST: wli-postgres.postgres.database.azure.com
  PG_DATABASE: my_app
  PG_USERNAME: uaid-myapp