# Use the official Node.js 16 image as a parent image
FROM node:18
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production
COPY . .
 
EXPOSE 3000
CMD [ "node", "index.js" ]