apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{.Values.serviceAccount.clientId}}
  labels:
    azure.workload.identity/use: "true"
  name: {{.Values.serviceAccount.name}}
  namespace: default